PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX paf: <http://givingsense.eu/sembib/data/tpt/paf2017/model#>

SELECT ?keyword ?year ?month
WHERE {
  ?article paf:has_key_word ?keyword.
  ?article paf:year ?year.
  OPTIONAL {?article paf:month ?month}
}